// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUvtKMo8CpppqFzCDu4gaWd8FBU4JkQ9A',
    appId: '1:1071033295398:web:03b85ac46e8212282abce7',
    messagingSenderId: '1071033295398',
    projectId: 'screenshot-blocker',
    authDomain: 'screenshot-blocker.firebaseapp.com',
    storageBucket: 'screenshot-blocker.firebasestorage.app',
    measurementId: 'G-8QWS9HH8EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGJcnGHD6ouMDa-Dws2gDCEChsdrldhag',
    appId: '1:1071033295398:android:5a985834671ae6b62abce7',
    messagingSenderId: '1071033295398',
    projectId: 'screenshot-blocker',
    storageBucket: 'screenshot-blocker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADTm9LIdY1jzm2z4QKf7chdNT7DQCwB7I',
    appId: '1:1071033295398:ios:224d81a571c02d422abce7',
    messagingSenderId: '1071033295398',
    projectId: 'screenshot-blocker',
    storageBucket: 'screenshot-blocker.firebasestorage.app',
    iosBundleId: 'com.example.screenshotBlocker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUvtKMo8CpppqFzCDu4gaWd8FBU4JkQ9A',
    appId: '1:1071033295398:web:04bec652b051aa962abce7',
    messagingSenderId: '1071033295398',
    projectId: 'screenshot-blocker',
    authDomain: 'screenshot-blocker.firebaseapp.com',
    storageBucket: 'screenshot-blocker.firebasestorage.app',
    measurementId: 'G-QKFDV24GS7',
  );
}
